### ISSUE TITLE
Help with Nav centering

### ISSUE THREAD

**Issue by wdet30** [wdetdigital/wdet-conversion#103]
Hey @artlogic, would you please give me a hand with the Nav. @metastange has reported the following issues.

Header/Global Nav		Nav does not appear to be centered
Header/Global Nav		"Donate" in nav are not center aligned
Header/Global Nav		Shows, Podcasts... etc. menu not centered top to bottom in blue bar

**Comment by artlogic** [comment]
I am going to need some screenshots for the first two, with direction as to where you want things to move.

**Comment by wdet30** [comment]
@metastange, please direct James how you want this lined up.
TY

**Comment by metastange** [comment]
Nav issue: Needs to move to the right and down slightly
![Screen Shot 2022-01-09 at 1 45 53 PM](https://user-images.githubusercontent.com/85897115/148696233-a10ebe87-691c-4ddc-9beb-34bbb5de5099.png)

Donate button: "Donate" needs to be moved down
![Screen Shot 2022-01-09 at 1 45 45 PM](https://user-images.githubusercontent.com/85897115/148696246-3327fb9c-1f17-4878-bb93-08d0ff3333e5.png)

**Comment by metastange** [comment]
The colors are also incorrect for the heart and the word "Donate" - they should match the outline.

**Comment by artlogic** [comment]
> Nav issue: Needs to move to the right and down slightly

How far to the right?

**Comment by artlogic** [comment]
> What is the most appropriate way to quantify this? I don't know how to provide additional guidance in this case. 

Generally you would point out something it should be lining up with, or markup up the imagine with a line showing where the edge should be.

**Comment by metastange** [comment]
Yellow line is the middle of the nav. It should line up with the center of the page (red line
![navigation alignment](https://user-images.githubusercontent.com/85897115/148699454-b523d21d-4e36-484c-a103-953a5b138a2f.png)
)

**Comment by artlogic** [comment]
That's no problem, but please be aware that the search button will make this appear to not be centered when it's in that position.

**Comment by wdet30** [comment]
@metastange , I can put the search button in the sidebar. It's there now please advise.

**Comment by wdet30** [comment]
I will take the search out of the nav

**Comment by metastange** [comment]
I would prefer to keep the search in the nav, not in the sidebar, otherwise it's not easily accessible in mobile. It was already aligned right in previous iterations of the review, so that's fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wdet30** [comment]
ok rolling it back

**Comment by artlogic** [comment]
I commented out my hack and it's good enough - I will update github shortly

**Comment by artlogic** [comment]
@wdet30 

I updated github with theme changes to make the nav centering official and to change the donate centered - but I noticed that github appears to be out of date, so you may want to look at my commits and apply them piecemeal - where are you keeping the official version of the theme?

**Comment by artlogic** [comment]
Last piece of this puzzle - the following site should solve the top to bottom nav centering:

```css
h1.site-title {
  margin: 0;
}
```

Removing myself from this - please re-add me if any of this doesn't work.

**Comment by wdet30** [comment]
Resolved with updated.

**Comment by artlogic** [comment]
Doesn't appear to be entirely fixed.

**Comment by artlogic** [comment]
@codingforapps can you take a look at this and resolve on dev?

**Comment by codingforapps** [comment]
before shot (what's in production site) for reference. please only pay attention to the styles and not the differences in menu items/order. these screenshots are from firefox on my mac, but i have also cross-referenced Safari and Chrome. 
<img width="1279" alt="Screen Shot 2022-05-04 at 2 03 15 PM" src="https://user-images.githubusercontent.com/6656745/166787892-5bf0c6fd-5fd0-444d-ada7-7566e0490a35.png">

after (what's in dev)
<img width="1280" alt="Screen Shot 2022-05-04 at 2 07 22 PM" src="https://user-images.githubusercontent.com/6656745/166788197-b70296c5-907a-4e51-94e5-7be4fe32824f.png">

**Comment by artlogic** [comment]
Changes applied in prodiuction, @codingforapps can you confirm?

**Comment by codingforapps** [comment]
@artlogic i'm seeing the changes are made and now this issue can be closed
