### ISSUE TITLE
No Listen Button

### ISSUE THREAD

**Issue by dmsanderswdet** [wdetdigital/wdet-conversion#118]

**Comment by artlogic** [comment]
We're going to need more details here. Platform or device. Browser. Screenshots. Who reported this?

**Comment by dmsanderswdet** [comment]
It came through the feedback portal.  I can see the "Listen Button" on my computer.  I haven't tried streaming it on the mobile app



Diane



Listen Live at  wdet.org<http://www.wdet.org/> or in the WDET mobile app<https://wdet.org/mobile/>

[cid:5088abf5-2547-42cb-878c-f043261c9670]

________________________________

**Comment by artlogic** [comment]
Issues like this are pretty difficult to track down without further details. Are you able to reach out to the person who gave this feedback?

**Comment by dmsanderswdet** [comment]
The message was received through a feedback portal.  I am able to see the "Listen" button on my computer

**Comment by artlogic** [comment]
I don't know what a feedback portal is, but it sounds like you have no way of communicating with people that use it? That will make tracking down these issues very difficult.

I'm going to assume the person is talking about the lack of a listen button in the header of the mobile site, but I can't be sure.

**Comment by dorothyhernandez** [comment]
@artlogic I can't tell who submitted it (maybe @dmsanderswdet we can change the survey to make it required people put their contact info) I'm 99% sure this is in reference to the lack of a listen button in the header of the mobile site. This is what it looked like on the old site:

![WDET](https://user-images.githubusercontent.com/91985309/151276214-ffc43849-5e2d-4424-a501-22e3577ea734.png)

Now there is no icon.

![WDET 101 9FM -](https://user-images.githubusercontent.com/91985309/151276267-5f6d3f88-2da7-445b-a959-1fe137140b77.png)

I know Tony added the "Listen Live" in the menu but I think the feedback is specifically in regards to the Listen icon.

**Comment by wdet30** [comment]
Resolved, in mobile there is no more listen button. There is a page. It can be accessed in the site navigation, this will take you to a listen player. 

Try on your phone.
https://wdet.org/listen-live/

**Comment by dorothyhernandez** [comment]
Reopening this to see if there is room for discussion on this topic. A more easily accessible Listen button would enhance the user experience. Eli Newman says the station did a heat map a few years back that showed that the radio stream feature is one of the most used features on the site.

**Comment by artlogic** [comment]
@wdet30 This issue is specifically about no listen button in the header on the mobile site. The direction is that we need something that's not hidden behind a hamburger menu. I'm sure @dmsanderswdet can provide more context from prior meeting minutes.

**Comment by wdet30** [comment]
I will have this resolved in a day or so.

Thanks,

Anthony Brown
WDET, Digital Distribution Manager
(o) 313-577-8748
www.wdet.org
[cid:9090e72a-95db-4f32-90ec-8d3ab3076d75]
________________________________

**Comment by wdet30** [comment]
Update 3/7/22: Sorry, I should have a fix soon.

**Comment by wdet30** [comment]
@artlogic about to make some changes here in style.css. Just testing.

**Comment by artlogic** [comment]
To dev, correct?

**Comment by wdet30** [comment]
Yes, things are going great.

Anthony Brown
WDET, Digital Distribution Manager
(o) 313-577-8748
www.wdet.org
[cid:93ebe35b-889b-4bb7-b75d-f7031e94040f]
________________________________

**Comment by codingforapps** [comment]
we have a working version updated on production site that we moved from dev. essentially there's two buttons appearing on mobile version now: donate and listen. we checked them across browser and device. we also took 'contact us' off the navigation since its excessively long (save that a future discussion) it is more straightforward. this meets our needs for the fundraiser. 

updates in the nearest future include: refine the design/usability of those buttons for desktop and mobile.

**Comment by artlogic** [comment]
@codingforapps I've been asked to review this work - but I don't see any updates to the repo here, and while I could start diffing the two sites, that's going to eat up hours. Can you please provide a detailed list of the code changes you made and update the repo accordingly?

**Comment by codingforapps** [comment]
no need to review or diff check. the changes should be consistent on both production and dev. i havent been updating the git repo, but if you need that I can investigate that. OR i can drop the code we added here in the thread?

**Comment by wdet30** [comment]
I suggest James give a look as well. You never know.

**Comment by artlogic** [comment]
I've got a couple of questions:

1. Are we abandoning the idea of a copy of the theme in version control?
2. What (if anything) do I actually need to review. I literally have no idea what you've changed.

**Comment by codingforapps** [comment]
@artlogic i think i mentioned what we changed but if you want to connect on the phone for clarification 3134043020 it's easier for me.

**Comment by artlogic** [comment]
All I need is a list of files, preferably with diffs. You'd like to communicate that verbally instead of here?

**Comment by codingforapps** [comment]
header.php 
styles.css

yes because i hate clarifying Qs within this thread

**Comment by artlogic** [comment]
@codingforapps and I spoke at length - she'll make the changes to the files in github, and I'm going to be comparing those with what's currently in production to see where we actually stand. I will then review those and make sure everything looks OK.

I'll email outside this issue with comments on the general process.

**Comment by artlogic** [comment]
@codingforapps header.php in production doesn't match what is in github (and I assume dev, I haven't checked). I've linked the production version here. Can you please resolve the differences and update github? Thanks.

https://gist.github.com/artlogic/9244b10e0cc4909064a1415dcaf3d4d3

**Comment by wdet30** [comment]
@codingforapps , the buttons are not hiding on a 13inch screen. Can you adjust the CSS to compensate? This was taken from a 13inch mac book pro.
<img width="1440" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/84190532/159538466-a84c25e5-189e-4436-80eb-67a30247b26c.png">

**Comment by codingforapps** [comment]
@artlogic Can you do a hard refresh on the page? I have a 13" macbook and checked Chrome like I see here. 

Shift-Command-R

**Comment by artlogic** [comment]
@codingforapps Unfortunately I've been directed by management to do no further work on this project until I receive confirmation from Mary that I can continue. Perhaps @wdet30 can help.

**Comment by wdet30** [comment]
It worked thanks. @artlogic

**Comment by wdet30** [comment]
@artlogic @codingforapps , we have gone as far as we can with the resources and the theme on this ticket.
