### ISSUE TITLE
Remove audio player on top of photos

### ISSUE THREAD

**Issue by dorothyhernandez** [wdetdigital/wdet-conversion#129]
See screenshot (showing up on content under "More stories" at the post level)

<img width="585" alt="Screen Shot 2022-01-31 at 11 02 48 AM" src="https://user-images.githubusercontent.com/91985309/151828594-e6b12705-b593-45db-b7ce-a7e556d7d272.png">

**Comment by Fw7424** [comment]
Looks like this complete. @dorothyhernandez if you feel this is complete can you confirm and close?

@codingforapps I know you mentioned wanted to have some sort of icon for the posts with Audio. Can you create a separate issue for to explore that option?

**Comment by codingforapps** [comment]
i can confirm, this issue was resolved when we resolved the "long scrolling on page" issue
