### ISSUE TITLE
Wrong name on author page

### ISSUE THREAD

**Issue by dorothyhernandez** [wdetdigital/wdet-conversion#133]
The wrong name is appearing as the author title in Laura Herberg's author bio page (not sure if it's happening for other authors, I need to go through more posts to see if this is an ongoing issue or just something that happened with this particular author page).

<img width="1379" alt="Screen Shot 2022-02-04 at 5 18 43 PM" src="https://user-images.githubusercontent.com/91985309/152610764-4294e9af-4ac3-4090-86f2-ffa3ec7d37b9.png">

This is what it looks like in the CMS:

<img width="653" alt="Screen Shot 2022-02-04 at 5 20 57 PM" src="https://user-images.githubusercontent.com/91985309/152610974-f5c7311d-2dad-4e8b-bc5a-122e82c53fed.png">

**Comment by artlogic** [comment]
https://wdet.org/wp-admin/post.php?post=125335&action=edit

Why can't I add an author?

**Comment by codingforapps** [comment]
Is this resolved? I checked out several of the author pages and they looked to have the right titles.

**Comment by dorothyhernandez** [comment]
No, it happened again (thanks for responding to this I totally forgot about posting about this last week). 

When you click on Hooper's name in this [post](https://wdet.org/2022/02/16/independent-restaurant-coalition-calls-for-congress-to-refill-the-restaurant-revitalization-fund/), you see LaToya's name on the page. 
https://wdet.org/author/rhooper/

<img width="447" alt="Screen Shot 2022-02-18 at 2 54 05 PM" src="https://user-images.githubusercontent.com/91985309/155003898-61a0224c-963b-4010-94ae-9d11c3b6e6af.png">

**Comment by artlogic** [comment]
Thanks for the example. I'll look into this.

**Comment by codingforapps** [comment]
Ok @dorothyhernandez  I'm curious how Laura's page (the first example) did have this issue... and now doesn't. 
@artlogic You did not change anything regarding this?

**Comment by artlogic** [comment]
Not at all. Does this also happen in dev?

**Comment by codingforapps** [comment]
No in Dev, Ryan's page is correct it says "Ryan Patrick Hooper"

**Comment by artlogic** [comment]
I'm going to take a database dump and see if I can find the root cause of this - please don't attempt to fix prior.

**Comment by dorothyhernandez** [comment]
Any updates on this? Ryan just messaged me to say LaToya's name is still at the top of his author page. https://wdet.org/author/Rhooper/

**Comment by Fw7424** [comment]
Looks like this was resolved. @dorothyhernandez can you confirm, and close if you feel it has been resolved?
