### ISSUE TITLE
Webpage Scrolling

### ISSUE THREAD

**Issue by dmsanderswdet** [wdetdigital/wdet-conversion#152]
Reaching the footer takes a long time.  Stories repeating

**Comment by wdet30** [comment]
@Fw7424 @dorothyhernandez @codingforapps 
Log onto the VPN and give a look at the dev site. Please let me know if we should present this to Jerome? We need to get him to make these calls. When it comes to how we present the news etc. https://wdetdev.wdet.org/

**Comment by wdet30** [comment]
Notes to self: "feature only three posts up top (because these are posts we want to highlight for our audience whether it's breaking news or a new podcast, etc.) we don't need featured and news and Detroit today. That would also help with the repeating posts"

**Comment by Fw7424** [comment]
Solutions presented. limit post count to 12 and removing the you may have missed section.

**Comment by codingforapps** [comment]
presentation for page length issue
![wdet-longpage-presentation-01](https://user-images.githubusercontent.com/6656745/163232879-e5c79f14-62aa-4bea-8ff3-f91e75acf291.png)
![wdet-longpage-presentation-02](https://user-images.githubusercontent.com/6656745/163232893-6c93f164-1b69-420b-9e00-bee64215da78.png)
![wdet-longpage-presentation-03](https://user-images.githubusercontent.com/6656745/163232897-ab89c43a-da1a-4bfb-9d8a-0bf717c90838.png)

**Comment by codingforapps** [comment]
Tony and I worked today on the proposed changes which are executed in the dev site. The post display is limited to 12 and the 'you may have missed' section is removed. The amount of scrolling is at a more comfortable level.

**Comment by wdet30** [comment]
I made the changes on the live site. What do you think?
Anthony Brown
WDET, Digital Distribution Manager
(o) 313-577-8748
www.wdet.org
[cid:34d8347a-c4c2-486a-8433-51a2597083e7]
________________________________

**Comment by wdet30** [comment]
Please reopen if this needs more work.
